### ISSUE TITLE
Getting undefined response from chatbot when using directline3

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#117]
Hi,
My bot is based on MS bot framework And I am using Directline3(Botium-CLI +Testmybot) to automate my bot. But when Bot response consists of image or button, it says undefined. Please help.
I am getting following error. Please let me know if you need any other information.
` bot response "[object Object]" missing expected property: senderID
    at _.forOwn
  
    at baseForOwn (C:\Users\dipali.khirwadkar\AppData\Roaming\npm\node_modules\botium-cli\node_modules\lodash\lodash.js:2996:24)
    at Function.forOwn (C:\Users\dipali.khirwadkar\AppData\Roaming\npm\node_modules\botium-cli\node_modules\lodash\lodash.js:13015:24)
    at Convo._compareObject (C:\Users\dipali.khirwadkar\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:135:9)
    at container.WaitBotSays.then (C:\Users\dipali.khirwadkar\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:88:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

debug('running testcase ' + convo.header.name)
const messageLog = []
const listenerMe = (container, msg) => {
  messageLog.push('#me: ' + msg.messageText)
}
const listenerBot = (container, msg) => {
  messageLog.push('#bot: ' + msg.messageText)
}
botiumContext.driver.on('MESSAGE_SENTTOBOT', listenerMe)
botiumContext.driver.on('MESSAGE_RECEIVEDFROMBOT', listenerBot)
const finish = (err) => {
  addContext(this, { title: 'Conversation Log', value: messageLog.join('\n') })
  botiumContext.driver.eventEmitter.removeListener('MESSAGE_SENTTOBOT', listenerMe)
  botiumContext.driver.eventEmitter.removeListener('MESSAGE_RECEIVEDFROMBOT', listenerBot)
  testcaseDone(err)
}
convo.Run(botiumContext.container)
  .then(() => {
    debug(convo.header.name + ' ready, calling done function.')
    finish()
  })
  .catch((err) => {
    debug(convo.header.name + ' failed: ' + util.inspect(err))
    finish(err)
  })`

**Comment by DipaliK9** [comment]
I updated Convo file and it worked for me. Thanks :)
