### ISSUE TITLE
Botium-cli-emulator -- config command fails with illegal operation on a directory read error

### ISSUE THREAD

**Issue by mohammednazim-tf** [codeforequity-at/botium-core#148]

**Comment by mohammednazim-tf** [comment]
I followed the steps given in "10 Minutes: Codeless Test Automation for IBM Watson Chatbots" article but unable to get through .  Did any body faced the below issue? Kindly help.

I am getting below errors

C:\>botium-cli emulator --config C:\node_modules\botium-core\botium
C:\Users\101086\AppData\Roaming\npm\node_modules\botium-cli\node_modules\yargs\y
args.js:1133
      else throw err
           ^

Error: FAILED: loading Botium configuration file C:\node_modules\botium-core\bot
ium: { Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:517:3)
    at tryReadSync (fs.js:340:20)
    at Object.readFileSync (fs.js:377:19)
    at loadConfigFile (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-c
li\node_modules\botium-core\src\BotDriver.js:29:40)
    at new BotDriver (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-cl
i\node_modules\botium-core\src\BotDriver.js:50:9)
    at module.exports (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-c
li\src\emulator\console\index.js:12:18)
    at handler (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-cli\src\
emulator\index.js:14:5)
    at Object.builder.handler (C:\Users\101086\AppData\Roaming\npm\node_modules\
botium-cli\bin\botium-cli.js:34:7)
    at Object.runCommand (C:\Users\101086\AppData\Roaming\npm\node_modules\botiu
m-cli\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\101086\AppData\Roaming\npm\nod
e_modules\botium-cli\node_modules\yargs\yargs.js:1046:30) errno: -4068, syscall:
 'read', code: 'EISDIR' }
    at loadConfigFile (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-c
li\node_modules\botium-core\src\BotDriver.js:39:15)
    at new BotDriver (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-cl
i\node_modules\botium-core\src\BotDriver.js:50:9)
    at module.exports (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-c
li\src\emulator\console\index.js:12:18)
    at handler (C:\Users\101086\AppData\Roaming\npm\node_modules\botium-cli\src\
emulator\index.js:14:5)
    at Object.builder.handler (C:\Users\101086\AppData\Roaming\npm\node_modules\
botium-cli\bin\botium-cli.js:34:7)
    at Object.runCommand (C:\Users\101086\AppData\Roaming\npm\node_modules\botiu
m-cli\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\101086\AppData\Roaming\npm\nod
e_modules\botium-cli\node_modules\yargs\yargs.js:1046:30)
    at Object.get [as argv] (C:\Users\101086\AppData\Roaming\npm\node_modules\bo
tium-cli\node_modules\yargs\yargs.js:989:21)
    at Object.<anonymous> (C:\Users\101086\AppData\Roaming\npm\node_modules\boti
um-cli\bin\botium-cli.js:68:3)
    at Module._compile (internal/modules/cjs/loader.js:722:30)

**Comment by codeforequity-at** [comment]
Obviously, you didn't follow it in detail, the command line makes no sense. Please use Stackoverflow for such questions! Thanks!
