### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ptedeschi** [codeforequity-at/botium-core#149]
Getting error when trying save conversation on botium-cli 0.0.31.

How to reproduce:

1. botium-cli emulator console --convos=./convo --config=./botium.json
2. interact with the bot
3. #SAVE conversation

Config file:
`{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "TEST",
      "CONTAINERMODE": "directline3",
	  "SCRIPTING_MATCHING_MODE": "regexp",
      "DIRECTLINE3_SECRET": "<secret>",
      "DIRECTLINE3_WEBSOCKET": true,
      "DIRECTLINE3_POLLINGINTERVAL": 1000
    }
  }
}
`

Observation: Saving a empty conversations is OK

**Comment by bchhun** [comment]
I'm getting the same error with the `botium-cli import "dialogflow-intents"` command.

The stacktrace looks like this:

```
WARNING: writing convo for intent "undefined" failed: TypeError: Cannot read property 'map' of undefined
    at Decompile.convo.conversation.forEach (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerTxt.js:179:21)
    at Array.forEach (<anonymous>)
    at CompilerTxt.Decompile (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerTxt.js:155:24)
    at ScriptingProvider.Decompile (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:142:21)
    at Object.module.exports.writeConvo (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/src/import/helpers.js:31:31)
    at intentEntries.forEach (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/src/import/dialogflowintents.js:44:32)
    at Array.forEach (<anonymous>)
    at importIntents (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/src/import/dialogflowintents.js:14:17)
    at async.series (/Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/src/import/dialogflowintents.js:249:9)
    at /Users/bchhun/.nvm/versions/node/v8.12.0/lib/node_modules/botium-cli/node_modules/async/dist/async.js:3880:24
```

**Comment by codeforequity-at** [comment]
Seems to be a bug, will evaluate it.

**Comment by codeforequity-at** [comment]
This one is fixed with the latest build (currently running, so in a few minutes 0.0.32 will be available).

**Comment by ptedeschi** [comment]
It's working! Thanks!
