### ISSUE TITLE
 Alexa AVS- unable to run test using botium-cli run mochawesome

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#193]
**Describe the bug**
I am trying to execute  command  botium-cli run mochawesome to test my skill. I have installed botium-cli and I am using connector alexa-avs
But if I run command npm run mocha, it works but  botium-cli run mochawesome doesn't work. I need report in mochawesome. Please let me know which command to use.
**Error log**
  "before all" hook:
     Error: Loading Botium plugin failed
      at Validate.Validate.then (**\node_modules\botium-cli\node_modules\botium-core\src\containers\PluginConnectorContainer.js:56:15)

[mochawesome] Report JSON saved to **[Path]

**Expected behavior**
It should execute command and mochawesome report should be created to the path specified in package.json.
```
"scripts": {
    "mocha": "mocha spec",
	"start": "node index.js",
      "test": "mocha --reporter spec --exit spec",
      "emulator": "npm install botium-cli && botium-cli emulator console --convos ./spec/convo --config ./botium.json",
      "emulatorBrowser": "npm install botium-cli && botium-cli emulator browser --convos ./spec/convo --config ./botium.json",
      "generateMochawesome": /path
  }
```

**Comment by codeforequity-at** [comment]
The alexa avs connector is not yet integrated into the Botium CLI. The command you are using is the right one. Please wait for the next Botium CLI build.

**Comment by DipaliK9** [comment]
I just need report in mochawesome if not botium-cli then please let me know which command should I use to using npm to get the result in mochawesome report.

**Comment by codeforequity-at** [comment]
Use this sample botium.json as template:
https://github.com/codeforequity-at/botium-bindings/blob/master/samples/watson/package.json

It uses botium-bindings and mocha to save testresult as mochawesome.

**Comment by DipaliK9** [comment]
I executed npm run test
But it says "mochawesome" reporter not found
"scripts": {
    "mocha": "mocha spec",
	 "test": "mocha --reporter mochawesome --reporter-options \"code=false,reportTitle=Test\"  --exit spec",
    "emulator": "npm install botium-cli && botium-cli emulator console --convos ./spec/convo",
	"emulatorBrowser": "npm install botium-cli && botium-cli emulator browser --convos ./spec/convo"
  }
** Error Log**
```
Error: invalid reporter "mochawesome"
    at Mocha.reporter (.\node_modules\mocha\lib\mocha.js:193:13)
    at Object.<anonymous> .\node_modules\mocha\bin\_mocha:368:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```


```

**Comment by codeforequity-at** [comment]
please look carefully at the package.json sample, especially the dependencies section

**Comment by DipaliK9** [comment]
Sorry to bother you again. But I double checked package.json. and it seems as expected. Still when I execute command 
>npm run test
 I am getting following error: 
 mocha --reporter mochawesome --reporter-options "code=false,reportTitle=Test"  --exit spec

```
"mochawesome" reporter not found
D:\Assigned Projects\SmartAisle\Bottle Genius\QA\Automation cases\node_modules\mocha\lib\mocha.js:193
      throw new Error('invalid reporter "' + reporter + '"');
      ^

Error: invalid reporter "mochawesome"
    at Mocha.reporter (D:\Assigned Projects\SmartAisle\Bottle Genius\QA\Automation cases\node_modules\mocha\lib\mocha.js:193:13)
    at Object.<anonymous> (D:\Assigned Projects\SmartAisle\Bottle Genius\QA\Automation cases\node_modules\mocha\bin\_mocha:368:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
```
Please see my package.json
```
 "devDependencies": {
    "botium-bindings": "^2.0.3",
    "botium-connector-alexa-avs": "../",
    "botium-core": "*",
    "mocha": "latest",
    "mochawesome": "latest"
  },
  "scripts": {
    "init-alexa-avs": "botium-connector-alexa-avs-init",
    "mocha": "mocha spec",
    "test": "mocha --reporter mochawesome --reporter-options \"code=false,reportTitle=Test\"  --exit spec",
    "emulator": "npm install botium-cli && botium-cli emulator console --convos ./spec/convo",
    "emulatorBrowser": "npm install botium-cli && botium-cli emulator browser --convos ./spec/convo"
  }
```

**Comment by DipaliK9** [comment]
This thing worked. Can be closed.
