### ISSUE TITLE
Alexa AVS-Error while installing botium-connector-alexa-avs

### ISSUE THREAD

**Issue by ChampNBM** [codeforequity-at/botium-core#195]
**Bug Description**
I am getting following error while installing botium-connector-alexa-avs
> npm install botium-connector-alexa-avs

**Error**
```
if not define         d npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\nod         e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\node         js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modul         es\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_module         s\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js         :284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm         \\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Assigned Projects\SmartAisle\Bottle Genius\QA\Automation cases\node_modules\speaker
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

**Comment by ChampNBM** [comment]
I installed python now I am getting following error:
```
..\node_modules\                                                                                                                           speaker\build\deps\mpg123\output.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the<Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe                                                                                                                           ` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\                                                                                                                           npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                                                                                                           s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd .\node_modules\speaker
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

> grpc@1.18.0 install .\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: ".\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_                                                                                                                           node.node" is installed via remote

> protobufjs@6.8.8 postinstall 
> node scripts/postinstall

npm WARN saveError ENOENT: no such file or directory, open 
npm WARN enoent ENOENT: no such file or directory, open ..\package.json'
npm WARN folder-2-2 No description
npm WARN folder-2 No repository field.
npm WARN folder-2 No README data
npm WARN folder-2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                                           )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 (node_modules\speaker):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 install: `node-gyprebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ botium-connector-alexa-avs@0.0.1
added 271 packages from 300 contributors and audited 18463 packages in 75.801s
found 0 vulnerabilities
```

**Comment by ujja** [comment]
Problem is related to nodejs->node-gyp->MsVisualStudio.

Try to install windows-build-tools (https://github.com/felixrieseberg/windows-build-tools) pls

**Comment by ChampNBM** [comment]
I executed command 
>npm install --global windows-build-tools
It installed without any error
Still getting the same error.
```
\node_modules\speaker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_m                                                                                                                           odules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\                                                                                                                           bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm                                                                                                                           \node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,please add the "/m" switch.
D:\.\node_modules\                                                                                                                         speaker\build\deps\mpg123\output.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe                                                                                                                           ` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\                                                                                                                           npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                                                                                                           s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\.\node_modules\speaker
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN folder-2 No description
npm WARN folder-2 No repository field.
npm WARN folder-2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                                           )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 (node_modules\speaker):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: speaker@0.3.1 install: `node-gyprebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ botium-connector-alexa-avs@0.0.1
updated 1 package and audited 5729 packages in 40.645s
found 0 vulnerabilities

```

**Comment by ujja** [comment]
Speaker is some optional module. You can ignore it:
npm install --no-optional

**Comment by ChampNBM** [comment]
I executed following command 
>./node_modules/.bin/botium-connector-alexa-avs-init

It gives me failed error as given below.
```
Authorizing device...
Device serial number: ********
Please login on https://amazon.com/us/code and enter [code]
Press enter after done
npm[15612]: src\node_file.cc:1311: Assertion `args[1]->IsInt32()' failed.
 1: 000000013F989055
 2: 000000013F962FE6
 3: 000000013F9630B1
 4: 000000013F92A687
 5: 000000013FF7B022
 6: 000000013FF7C4CD
 7: 000000013FF7B559
 8: 000000013FF7B43B
 9: 000000477EB841C1
```

**Comment by ujja** [comment]
create other issue pls
