### ISSUE TITLE
Alexa AVS- Getting Bot Says nothing/Permission denied error

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#203]
I am constantly getting Bot says nothing error for my bot. But when I used debug mode, I realized I am facing 2 issues.

1. I Checked for generic skill. E.g. Ask for weather to alexa and In mochawesome report, it says bot says nothing. However, when I executed same in debug mode, I am getting following error with audio response.

`PERMISSION_DENIED: This API method requires billing to be enabled. Please enable billing on project #**** by visiting https://console.developers.google.com/billing/enable?project=**** then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.`

I am not able to enable the billing and tried to create new billing profile but it is not accepting card details.
I have one more question, I was looking for free tool and after 1 year do I have to pay for this?
Is there any other alternative?

2. If I invoke my skill, I am getting same error now. But still response from alexa is blank. It does not even say that I am not sure.

Note: Skill is getting invoked if I do using actual device.
For Reference: #188 
Thanks

**Comment by ujja** [comment]
This is coming from google, so text-to-speech, or speech-to-text API is throwing it.

There are no good free APIs for TTS and STT.

It is possible to create Google STT and TTS by different users, but it does not helps too mutch.

We support now Amazon services for STT and TTS, but they aren't free.

**Comment by DipaliK9** [comment]
#1. There is Always free AWS account as I can see. I am not sure if it is useful for me. Can you please help, which one I should go for.
https://aws.amazon.com/free/?awsf.Free%20Tier%20Types=categories%23alwaysfree
#2. what could be the reason for : 

    If I invoke my skill, I am getting same error now. But still response from alexa is blank. It does not even say that I am not sure.

Note: Skill is getting invoked if I do using actual device.

**Comment by DipaliK9** [comment]
Also wanted to confirm that my skill is specific to a business organization not public. Does it matter?
Does factors like time zone matters in this case?
However, as you said I checked and I am getting response from actual Alexa device.
Please help!!

**Comment by ujja** [comment]
Flow is the following:
1) sending text to google text to speech API
2) sending speech to amazon alexa API
3) sending speech response to google speech to text API.

You got this error from Google. It means possibly that the first step is not well executed, and so Amazon got an empty speech. And Amazon answers with empty speech response.

If you are using your actual Alexa device, then it sends speech to amazon alexa API direct.

**Comment by DipaliK9** [comment]
I get the response for weather update but not for my skill when I debug.(Without debug option I just get permission denied message for all). So not sure if it is issue with google API (step 1.)
Do you suggest that I should use Amazon polly?
There is Always free AWS account as I can see. I am not sure if it is useful for me. Can you please help, which one I should go for.
https://aws.amazon.com/free/?awsf.Free%20Tier%20Types=categories%23alwaysfree

**Comment by ujja** [comment]
hmmm, thats strange. Attach log please, maybe i see more.

Im sure it is Google. See error message "Please enable billing on project #**** by visiting https://console.developers.google.com/billing/enable"

I dont know differences in pricing and limitations. But I suppose they are almost the same.

I dont know amazon accounts well

**Comment by DipaliK9** [comment]
Please see log as given below. Facing randomly 2 issues.
1. Sometimes No Alexasaid.MP3 files gets generated. and bot says nothing in response.
2.Sometimes the file gets generated but it says Sorry I am not sure about that.
Unable to invoke skill. Same invoke statement works when used in actual device. 
Please let me know if you need any other information. But please help me on this.


```

$ npm run test

> @ test 
> mocha --reporter mochawesome --reporter-options "code=false,reportTitle=Test"--exit spec

2019-01-31T10:14:48.025Z botium-bindings-main Botium Bindings args: { convodirs:[ 'spec\\convo' ],
  expandConvos: true,
  expandUtterancesToConvos: false }
2019-01-31T10:14:48.052Z botium-BotDriver Loaded Botium configuration file ./botium.json
2019-01-31T10:14:48.055Z botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'Botium Project Alexa AVS',
  TEMPDIR: 'botiumwork',
  CLEANUPTEMPDIR: true,
  WAITFORBOTTIMEOUT: 10000,
  SIMULATE_WRITING_SPEED: false,
  DOCKERCOMPOSEPATH: 'docker-compose',
  DOCKERMACHINEPATH: 'docker-machine',
  DOCKERMACHINE: false,
  DOCKERIMAGE: 'node:boron',
  DOCKERUNIQUECONTAINERNAMES: false,
  DOCKERSYSLOGPORT_RANGE: '47100-47299',
  BOT_HEALTH_STATUS: 200,
  SLACK_PUBLISHPORT_RANGE: '46100-46299',
  FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  SIMPLEREST_METHOD: 'GET',
  WEBSPEECH_SERVER_PORT: 46050,
  WEBSPEECH_LANGUAGE: 'en-US',
  WEBSPEECH_CLOSEBROWSER: true,
  SCRIPTING_TXT_EOL: '\n',
  SCRIPTING_XLSX_EOL_SPLIT: '\r',
  SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  SCRIPTING_XLSX_STARTROW: 1,
  SCRIPTING_XLSX_STARTCOL: 'A',
  SCRIPTING_NORMALIZE_TEXT: true,
  SCRIPTING_ENABLE_MEMORY: false,
  SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  SCRIPTING_UTTEXPANSION_MODE: 'all',
  SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
  ASSERTERS: [],
  LOGIC_HOOKS: [],
  CONTAINERMODE: 'alexa-avs',
  ALEXA_AVS_AVS_CLIENT_ID:
  ALEXA_AVS_AVS_CLIENT_SECRET:********
  ALEXA_AVS_AVS_REFRESH_TOKEN: ********
  ALEXA_AVS_AVS_LANGUAGE_CODE: 'en_US',
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_PRIVATE_KEY:  ********
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_CLIENT_EMAIL: ********
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_LANGUAGE_CODE: 'en_US',
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_PRIVATE_KEY:****************
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_CLIENT_EMAIL:********
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_LANGUAGE_CODE: 'en_US' }
2019-01-31T10:14:48.429Z botium-ScriptingProvider Using matching mode: includeLowerCase
2019-01-31T10:14:48.429Z botium-asserterUtils Loaded Default asserter - [ 'BUTTONS', 'MEDIA', 'PAUSE_ASSERTER' ]
2019-01-31T10:14:48.430Z botium-asserterUtils Loaded Default logic hook - [ 'PAUSE', 'WAITFORBOT' ]
2019-01-31T10:14:48.435Z botium-ScriptingProvider ReadConvosFromDirectory(spec\convo) found filenames: BG.convo.txt
2019-01-31T10:14:48.439Z botium-ScriptingProvider ReadConvosFromDirectory(spec\convo) found convos:
 1 convo1 ({ filename: 'BG.convo.txt' }): Line 6: #me - Alexa, [Invoke Statement]  | Line 7: #bot -
2019-01-31T10:14:48.439Z botium-ScriptingProvider ReadConvosFromDirectory(spec\convo) found utterances:

2019-01-31T10:14:48.439Z botium-ScriptingProvider ExpandConvos - Using utterances expansion mode: all
2019-01-31T10:14:48.440Z botium-bindings-main ready reading convos and utterances, number of test cases: (1).
2019-01-31T10:14:48.440Z botium-bindings-main adding test case 1 convo1
 Botium Test Suite for <Unknown Module>
2019-01-31T10:14:48.445Z botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Botium Project Alexa AVS',
  TEMPDIR: 'botiumwork',
  CLEANUPTEMPDIR: true,
  WAITFORBOTTIMEOUT: 10000,
  SIMULATE_WRITING_SPEED: false,
  DOCKERCOMPOSEPATH: 'docker-compose',
  DOCKERMACHINEPATH: 'docker-machine',
  DOCKERMACHINE: false,
  DOCKERIMAGE: 'node:boron',
  DOCKERUNIQUECONTAINERNAMES: false,
  DOCKERSYSLOGPORT_RANGE: '47100-47299',
  BOT_HEALTH_STATUS: 200,
  SLACK_PUBLISHPORT_RANGE: '46100-46299',
  FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  SIMPLEREST_METHOD: 'GET',
  WEBSPEECH_SERVER_PORT: 46050,
  WEBSPEECH_LANGUAGE: 'en-US',
  WEBSPEECH_CLOSEBROWSER: true,
  SCRIPTING_TXT_EOL: '\n',
  SCRIPTING_XLSX_EOL_SPLIT: '\r',
  SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  SCRIPTING_XLSX_STARTROW: 1,
  SCRIPTING_XLSX_STARTCOL: 'A',
  SCRIPTING_NORMALIZE_TEXT: true,
  SCRIPTING_ENABLE_MEMORY: false,
  SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  SCRIPTING_UTTEXPANSION_MODE: 'all',
  SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
  ASSERTERS: [],
  LOGIC_HOOKS: [],
  CONTAINERMODE: 'alexa-avs',
  ALEXA_AVS_AVS_CLIENT_ID:********
  ALEXA_AVS_AVS_CLIENT_SECRET: ********
  ALEXA_AVS_AVS_REFRESH_TOKEN:********
  ALEXA_AVS_AVS_LANGUAGE_CODE: 'en_US',
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_PRIVATE_KEY:********
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_CLIENT_EMAIL:********
  ALEXA_AVS_TTS_GOOGLE_CLOUD_TEXT_TO_SPEECH_LANGUAGE_CODE: 'en_US',
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_PRIVATE_KEY:********
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_CLIENT_EMAIL:********
  ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_LANGUAGE_CODE: 'en_US' }
2019-01-31T10:14:48.446Z botium-BotDriver Build - Sources : { LOCALPATH: '.',
  GITPATH: 'git',
  GITBRANCH: 'master',
  GITDIR: '.' }
2019-01-31T10:14:48.446Z botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER:true }
2019-01-31T10:14:48.518Z botium-PluginConnectorContainer Loading Botium plugin from alexa-avs failed - { Error: Cannot find module 'alexa-avs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at tryLoadPlugin (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs                                                                                                                           \node_modules\botium-core\src\containers\PluginConnectorContainer.js:16:20)
    at Validate.Validate.then (D:\Automation Cases-Bevmo\Bevmo_botium-connector-                                                                                                                           alexa-avs\node_modules\botium-core\src\containers\PluginConnectorContainer.js:45                                                                                                                           :29) code: 'MODULE_NOT_FOUND' }
2019-01-31T10:14:49.381Z botium-PluginConnectorContainer Botium plugin botium-connector-alexa-avs loaded
2019-01-31T10:14:49.381Z botium-connector-alexa-avs-main Validate called
2019-01-31T10:14:58.605Z botium-connector-alexa-avs-avs Validate called
2019-01-31T10:14:58.606Z botium-connector-alexa-avs-main Build called
2019-01-31T10:14:58.839Z botium-connector-alexa-avs-avs Build called
(node:17496) ExperimentalWarning: The http2 module is an experimental API.
2019-01-31T10:15:00.741Z botium-connector-alexa-avs-avs Access token acquired
2019-01-31T10:15:00.745Z botium-connector-alexa-avs-avs AVS http2-client created
2019-01-31T10:15:00.748Z botium-connector-alexa-avs-avs Downchannel created { ':method': 'GET',
  ':scheme': 'https',
  ':path': '/v20160207/directives',
  authorization:
   ********}
2019-01-31T10:15:00.751Z botium-connector-alexa-avs-main Start called
2019-01-31T10:15:00.752Z botium-bindings-main running testcase1 convo1
2019-01-31T10:15:00.756Z botium-Convo convo1/Line 6: user says {
  "sender": "me",
  "channel": null,
  "messageText": "Alexa, [Invoke Statement]",
  "stepTag": "Line 6",
  "not": false,
  "asserters": [],
  "logicHooks": []
}
2019-01-31T10:15:00.757Z botium-connector-alexa-avs-main UserSays called
2019-01-31T10:15:00.757Z botium-connector-alexa-avs-main User text "Alexa,[Invoke Statement]" converting to speech...
2019-01-31T10:15:02.321Z botium-connector-alexa-avs-main User text "Alexa,[Invoke Statement]" conversion to speech succeeded
2019-01-31T10:15:02.321Z botium-connector-alexa-avs-main Alexa answering...
2019-01-31T10:15:02.322Z botium-connector-alexa-avs-avs UserSays called
2019-01-31T10:15:02.330Z botium-connector-alexa-avs-avs UserSays request {
  ":method": "POST",
  ":scheme": "https",
  ":path": "/v20160207/events",
  "authorization": "Bearer  ******"
}
2019-01-31T10:15:02.335Z botium-connector-alexa-avs-avs Downchannel create status: {
  ":status": 200,
  "access-control-allow-origin": "*",
  "x-amzn-requestid": "0aa0e5fffe1c35ac-000004cb-000314e6-22f036475cfd4411-0fd02c1e-1",
  "content-type": "multipart/related; boundary=------abcde123; type=application/json"
}
2019-01-31T10:15:05.065Z botium-connector-alexa-avs-avs Downchannel data received
--------abcde123
Content-Type: application/json

{"directive":{"header":{"namespace":"SpeechRecognizer","name":"StopCapture","messageId":"4ccacb6c-ab14-4131-b4c9-4e9e7f3d0928","dialogRequestId":"126631a1-2541-11e9-b164-3d8a6ac147e3"},"payload":{}}}
--------abcde123

2019-01-31T10:15:05.612Z botium-connector-alexa-avs-avs UserSays response, multipart 0: { headers: { 'Content-Type': 'application/json; charset=UTF-8' },
  body:
   <Buffer 0d 0a 7b 22 64 69 72 65 63 74 69 76 65 22 3a 7b 22 68 65 61 64 65 72 22 3a 7b 22 6e 61 6d 65 73 70 61 63 65 22 3a 22 53 79 73 74 65 6d 22 2c 22 6e 61 ... >,
  meta: { body: { byteOffset: [Object] } } }
2019-01-31T10:15:05.612Z botium-connector-alexa-avs-avs UserSays response, multipart 0 Body:
{"directive":{"header":{"namespace":"System","name":"SetEndpoint","messageId":"8b4c344e-a992-4888-b47e-b46480933385","dialogRequestId":"126631a1-2541-11e9-b164-3d8a6ac147e3"},"payload":{"endpoint":"https://avs-alexa-na.amazon.com"}}}

2019-01-31T10:15:05.612Z botium-connector-alexa-avs-avs UserSays response, multipart 1: { headers: { 'Content-Type': 'application/json; charset=UTF-8' },
  body:
   <Buffer 0d 0a 7b 22 64 69 72 65 63 74 69 76 65 22 3a 7b 22 68 65 61 64 65 72 22 3a 7b 22 6e 61 6d 65 73 70 61 63 65 22 3a 22 53 70 65 65 63 68 53 79 6e 74 68 ... >,
  meta: { body: { byteOffset: [Object] } } }
2019-01-31T10:15:05.612Z botium-connector-alexa-avs-avs UserSays response, multipart 1 Body:
{"directive":{"header":{"namespace":"SpeechSynthesizer","name":"Speak","messageId":"197d3987-c0ad-450c-966e-a26fdd672903","dialogRequestId":"126631a1-2541-11e9-b164-3d8a6ac147e3"},"payload":{"url":"cid:DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e_245590730","format":"AUDIO_MPEG","token":"amzn1.as-ct.v1.Domain:Global:Fallback#ACRI#DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e"}}}

2019-01-31T10:15:05.612Z botium-connector-alexa-avs-avs UserSays response, multipart 2: { headers:
   { 'Content-ID':
      '<DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e_245590730>',
     'Content-Type': 'application/octet-stream' },
  body:
   <Buffer 0d 0a 49 44 33 04 00 00 00 00 00 23 54 53 53 45 00 00 00 0f 00 00 03 4c 61 76 66 35 37 2e 37 31 2e 31 30 30 00 00 00 00 00 00 00 00 00 00 00 ff f3 64 ... >,
  meta: { body: { byteOffset: [Object] } } }
2019-01-31T10:15:05.613Z botium-connector-alexa-avs-avs Found Content Payload with CID <DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e_245590730>
2019-01-31T10:15:05.613Z botium-connector-alexa-avs-avs Found JSON Payload of type application/json; charset=UTF-8
2019-01-31T10:15:05.613Z botium-connector-alexa-avs-avs Found JSON Payload of type application/json; charset=UTF-8
2019-01-31T10:15:05.613Z botium-connector-alexa-avs-avs Found SpeechSynthesizer/Speak directive { header:
   { namespace: 'SpeechSynthesizer',
     name: 'Speak',
     messageId: '197d3987-c0ad-450c-966e-a26fdd672903',
     dialogRequestId: '126631a1-2541-11e9-b164-3d8a6ac147e3' },
  payload:
   { url:
      'cid:DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e_245590730',
     format: 'AUDIO_MPEG',
     token:
      'amzn1.as-ct.v1.Domain:Global:Fallback#ACRI#DeviceTTSRendererV4_f70f8dcd-3cf8-4008-b567-4f262e4d8b3e' } }
2019-01-31T10:15:05.621Z botium-connector-alexa-avs-main Alexa answered succesfull
2019-01-31T10:15:05.621Z botium-connector-alexa-avs-main Answer converting to wav, format "AUDIO_MPEG", size 9553...
2019-01-31T10:15:05.766Z botium-connector-alexa-avs-main Alexa converted to wav
2019-01-31T10:15:05.766Z botium-connector-alexa-avs-main Answer converting to text...
2019-01-31T10:15:06.746Z botium-connector-alexa-avs-main Answer conversion failed, format "AUDIO_MPEG", size 9553: Error: 7 PERMISSION_DENIED: This API method requires billing to be enabled. Please enable billing on project #67968065440 by visiting https://console.developers.google.com/billing/enable?project=67968065440 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.
2019-01-31T10:15:06.746Z botium-connector-alexa-avs-main Answer handling ready, processed 1 audio responses.
2019-01-31T10:15:06.747Z botium-Convo convo1 wait for bot null
2019-01-31T10:15:16.750Z botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
    at timeoutRequest (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\helpers\Queue.js:46:18)
    at Timeout.timeoutCallback [as _onTimeout] (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:4936:13)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
2019-01-31T10:15:16.751Z botium-Convo convo1: bot says undefined
2019-01-31T10:15:16.751Z botium-Convo Error: convo1/Line 7: bot says nothing
    at scriptingEvents.onBotStart.then.then (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:247:33)
2019-01-31T10:15:16.753Z botium-bindings-main Test Case "convo1" failed: { TranscriptError: Error: convo1/Line 7: bot says nothing
    at async.waterfall (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:160:25)
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:473:16
    at next (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:5329:29)
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:969:16
    at runConversation (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:144:15)
    at async.mapSeries (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:317:9)
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:1140:9
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:473:16
    at iterateeCallback (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:988:17)
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:969:16
    at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:1137:13
    at convoStepDone (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:193:11)
    at scriptingEvents.onBotStart.then.then (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:253:24)
  name: 'TranscriptError',
  transcript:
   Transcript {
     steps: [ [TranscriptStep], [TranscriptStep] ],
     scriptingMemory: {},
     convoBegin: 2019-01-31T10:15:00.754Z,
     convoEnd: 2019-01-31T10:15:16.751Z,
     err:
      Error: convo1/Line 7: bot says nothing
          at scriptingEvents.onBotStart.then.then (D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\botium-core\src\scripting\Convo.js:247:33) } }
    1) convo1
2019-01-31T10:15:16.756Z botium-connector-alexa-avs-main Stop called
2019-01-31T10:15:16.756Z botium-connector-alexa-avs-avs Stop called
2019-01-31T10:15:16.757Z botium-connector-alexa-avs-main Clean called
2019-01-31T10:15:16.757Z botium-connector-alexa-avs-avs Clean called
2019-01-31T10:15:16.758Z botium-connector-alexa-avs-avs Downchannel closed
2019-01-31T10:15:16.759Z botium-BaseContainer Cleanup rimrafing temp dir D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\botiumwork\Botium-Project-Alexa-AVS-20190131-154448-AhySL


  0 passing (28s)
  1 failing

  1) Botium Test Suite for <Unknown Module>
       convo1:
     TranscriptError: Error: convo1/Line 7: bot says nothing
      at async.waterfall (node_modules\botium-core\src\scripting\Convo.js:160:25)
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:473:16
      at next (node_modules\async\dist\async.js:5329:29)
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:969:16
      at runConversation (node_modules\botium-core\src\scripting\Convo.js:144:15)
      at async.mapSeries (node_modules\botium-core\src\scripting\Convo.js:317:9)
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:1140:9
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:473:16
      at iterateeCallback (node_modules\async\dist\async.js:988:17)
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:969:16
      at D:\Automation Cases-Bevmo\Bevmo_botium-connector-alexa-avs\node_modules\async\dist\async.js:1137:13
      at convoStepDone (node_modules\botium-core\src\scripting\Convo.js:193:11)
      at scriptingEvents.onBotStart.then.then (node_modules\botium-core\src\scripting\Convo.js:253:24)



[mochawesome] Report JSON saved to

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `mocha --reporter mochawesome --reporter-options "code=false,reportTitle=Test"  --exit spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    


```

**Comment by ujja** [comment]
Log says: Exception is coming from Google Speech to Text API

`botium-connector-alexa-avs-main Answer conversion failed, format "AUDIO_MPEG", size 9553: Error: 7 PERMISSION_DENIED...`

**Comment by DipaliK9** [comment]
Yes sometimes it gives permission denied error But I can hear response in Alexasaid.MP3 and it says  I am not sure about that. However, same invoke statement works in my alexa device.

**Comment by DipaliK9** [comment]
Billing error got resolved. So logging another issue #213 for Alexa not responding as expected.
