### ISSUE TITLE
Unable to download botium-cli

### ISSUE THREAD

**Issue by nidhi-m25** [codeforequity-at/botium-core#320]
**Unable to install botium cli**
Botium CLI using the below comand- 
npm install -g botium-cli 

Error-->

`pm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/codeforequity-at/jsonpath.git
npm ERR!
npm ERR! undefined
npm ERR! exited with error code: 128`

Botium standalone is download from the 
> http://botium-artifacts.s3-website-eu-west-1.amazonaws.com/

and ran the botium-cli run
Botium Test-Suite

    1) "before all" hook

 

  0 passing (27ms)

  1 failing

  1) Botium Test-Suite

       "before all" hook:

     Error: Cannot find module 'esprima'

1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.

      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
      at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
      at Function.resolve (internal/modules/cjs/helpers.js:30:19)
      at Object.<anonymous> (C:\snapshot\botium-cli\node_modules\botium-core\node_modules\jsonpath\lib\aesprim.js:4:20)
      at Module._compile (pkg/prelude/bootstrap.js:1254:22)
      at Object.<anonymous> (C:\snapshot\botium-cli\node_modules\botium-core\node_modules\jsonpath\lib\aesprim.js:15:11)
      at Module._compile (pkg/prelude/bootstrap.js:1254:22)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
      at Module.load (internal/modules/cjs/loader.js:610:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:549:12)

Note-> node module esprima is already downloaded.

**Comment by nidhi-m25** [comment]
Any updates team?

**Comment by codeforequity-at** [comment]
no, research ongoing why the precompiled thing is not working.
For the first problem (npm install -g botium-cli), no idea why this is not working for you. This is more a Git or NPM problem than a Botium problem.

**Comment by nidhi-m25** [comment]
Are both the issues related ?

https://github.com/codeforequity-at/botium-connector-directline3/issues/27

**Comment by codeforequity-at** [comment]
There is a component referenced which is download from Github on installation, but the git call fails with error code 128 - there is a very broad range of things this could mean, we wrote done some of them here: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/28934174/Git+Error+128

**Comment by codeforequity-at** [comment]
As there are a growing number of referenced libraries depending on dynamic module resolution, we are forced to abandon the precompiled version of the Botium-CLI. There will be a docker image serving the same purpose very soon.

**Comment by codeforequity-at** [comment]
Botium CLI docker image available now
https://hub.docker.com/r/botium/botium-cli
