### ISSUE TITLE
getting "TranscriptError" error message

### ISSUE THREAD

**Issue by siliconberry** [codeforequity-at/botium-core#321]
Hello, 
Newbie here.. I getting following error whenever I run botium-cli run command.

  Botium Test-Suite
    1) HelloWorld-A2
    2) HelloWorld-A5

  0 passing (698ms)
  2 failing

  1) Botium Test-Suite
       HelloWorld-A2:
   **###   TranscriptError: Error: HelloWorld-A2/Cell B3: Expected bot response (on Cell A2: #me - hello bot!) "You said: hello bot!" to match one of "Hello, meat bag! How can I help you ?"**
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:214:25
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at next (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:4584:24)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:192:15
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:383:9
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:252:13
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at iterateeCallback (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:417:21)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:249:17
      at convoStepDone (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:258:11)
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:335:28

  2) Botium Test-Suite
       HelloWorld-A5:
     **### TranscriptError: Error: HelloWorld-A5/Cell B6: Expected bot response (on Cell A5: #me - hey dude) "You said: hey dude" to match one of "Hello, meat bag! How can I help you ?"**
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:214:25
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at next (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:4584:24)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:192:15
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:383:9
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:252:13
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at iterateeCallback (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:417:21)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:249:17
      at convoStepDone (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:258:11)
      at /usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:335:28

**Comment by codeforequity-at** [comment]
This is what a failing test case looks like.
