### ISSUE TITLE
Hyperlink check problem

### ISSUE THREAD

**Issue by xmichele** [codeforequity-at/botium-core#373]
**Describe the bug**
Hello I was initially useing botium-cli version of June with LINK feature working well.
Recently I updated to botium-cli 0.5.4 and noticed that probably this keyword has been removd and replaced with HASLINK keyword provided by botium-asserter-basiclink.
Now I got the error Cannot read property 'includes' of undefined ,  maybe caused by other npm WARN in installation phase.

Before running the test I run npm install --save botium-asserter-basiclink in my botium folder and added in my botium.json under myCapabilities:

 "ASSERTERS": [{
"ref": "HASLINK",
"src": "botium-asserter-basiclink"
}] 

I also checked https://npm.community/t/cannot-read-property-match-of-undefined/203

In my convo I have .. 

#bot  
HASLINK https://myURLToCheck

**Screenshots and Log files**
INSTALL PHASE 
.
.
npm WARN saveError ENOENT: no such file or directory, open '/app/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/app/package.json'
npm WARN botium-asserter-basiclink@0.0.6 requires a peer of botium-core@^1.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.

+ botium-asserter-basiclink@0.0.6
added 14 packages from 11 contributors and audited 28 packages in 1.558s
found 0 vulnerabilities
---------------
TEST 
.
.
  1) Botium Test-Suite
       BOT_TEST:
     TranscriptError: BOT_TEST/Line 6: assertion error - Cannot read property 'includes' of undefined
      at async.waterfall (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:225:25)
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at next (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:4584:24)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at runConversation (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:203:15)
      at async.mapSeries (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:437:9)
      at err (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:252:13)
      at wrapper (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:272:20)
      at iterateeCallback (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:417:21)
      at /usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:325:20
      at _iteratee (/usr/local/lib/node_modules/botium-cli/node_modules/async/dist/async.js:249:17)
      at convoStepDone (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:269:11)
      at scriptingEvents.assertConvoStep.then.catch (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/Convo.js:395:28)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:229:7)
	  
	  botium-asserter-basiclink

**Botium Version**
botium-cli 0.5.4

**Comment by xmichele** [comment]
tryed with new 0.0.55 and HASLINK. Seems to work well. The only problem is that if I put only a substring of the link provided from the chatbot, the test passes and passes also if it leads to 404 in a normal browser
I'm using "SCRIPTING_MATCHING_MODE":"include" but I didn't thought it affects link checking feature

**Comment by codeforequity-at** [comment]
botium-asserter-basiclink is for assertions that a hyperlink matching the pattern is part of the bot reponse, nothing more. It uses the same matching logic as the text asserter. 
asserting that the link is actually pointing to a valid URL resource is part of the paid botium box plans.

**Comment by xmichele** [comment]
But for valid , didn't mean that response code is not 4xx as well?

**Comment by codeforequity-at** [comment]
no, it just asserts if the link is part of the bot response
