### ISSUE TITLE
Botium automatically adds hyperlinks to the bot response and fails the test cases

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#389]
I am currently testing the botium EE 1.7.3 with Generic HTTP/JSON Chatbot technology.

When I trying to run the test case with the following bot response, provided the hyperlink asserter which is running by default.

`<h1><span style=\"background-color: #FFFF00\">ADLC</span> <span style=\"background-color: #FFFF00\">installation</span></h1>To <span style=\"background-color: #FFFF00\">install</span> project related software, please follow the steps to raise wasp request: 1.Please navigate to portal 2.App Store 3.Request 4.My Requests 5.IT Services 6.Software Requisition`

The test case fails as the hyperlink asserter automatically adds the hyperlink to the response and fails the test case as follows

```
2019-09-26T13:44:39.880Z: 2019-09-26T13:44:39.843Z botium-ScriptingProvider assertBotResponse sdscf/Line 6 (Line 3: #me - ADLC installation) BOT: ADLC installationTo install project related software, please follow the steps to raise wasp request: 1.Please navigate to portal 2.App Store 3.Request 4.My Requests 5.IT Services 6.Software Requisition = CDC installationTo install project related software, please follow the steps to raise wasp request: 1.Please navigate to portal 2.App Store 3.Request 4.My Requests 5.IT Services 6.Software Requisition ...

2019-09-26T13:44:39.880Z: 2019-09-26T13:44:39.842Z botium-ScriptingMemory fill start: {}

2019-09-26T13:44:40.974Z: 2019-09-26T13:44:40.963Z botium-asserter-hyperlink Results of links: [ UrlValidation {
    url: 'http://2.App',
    description: 'OK',
    statusCode: 200,
    expectedStatus: [ 200 ],
    valid: true },
  UrlValidation {
    url: 'http://4.My',
    description: 'OK',
    statusCode: 200,
    expectedStatus: [ 200 ],
    valid: true },
  UrlValidation {
    url: 'http://5.IT',
    description: 'getaddrinfo ENOTFOUND 5.it 5.it:80',
    statusCode: 404,
    expectedStatus: [ 200 ],
    valid: false },
  UrlValidation {
    url: 'http://6.Software',
    description: 'getaddrinfo ENOTFOUND 6.software 6.software:80',
    statusCode: 404,
    expectedStatus: [ 200 ],
    valid: false } ]

2019-09-26T13:44:40.975Z: 2019-09-26T13:44:40.964Z botium-Convo Error: sdscf/Line 6: assertion error - Error: Line 6: FAILURE: http://5.IT getaddrinfo ENOTFOUND 5.it 5.it:80 Actual: 404 Expected: 200 | FAILURE: http://6.Software getaddrinfo ENOTFOUND 6.software 6.software:80 Actual: 404 Expected: 200
    at Promise.all.then.results (/app/agent/node_modules/botium-asserter-hyperlink/src/HyperLinkAsserter.js:105:31)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at scriptingEvents.assertConvoStep.then.then.catch (/app/agent/node_modules/botium-core/src/scripting/Convo.js:349:35)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

2019-09-26T13:44:43.597Z: 2019-09-26T13:44:43.587Z botium-BaseContainer Cleanup rimrafing temp dir /app/agent/botiumwork/Manual-Test-Session-testtest-20190926-134439-9yKT2

2019-09-26T13:44:44.322Z: Job completed
```

The test cases are getting passed after i remove the default hyperlink asserters. But there are places where i need to validate the hyperlinks also.

Please help me to run the test cases after enabling the hyperlink asserter so that it will not affect the other test cases.

**Comment by codeforequity-at** [comment]
What Botium Box Version are you using ? With the latest 1.7.5 the hyperlink asserter has been updated.

**Comment by Aishwarya-J-S** [comment]
We are currently using the Enterprise Edition 1.7.3.

**Comment by Aishwarya-J-S** [comment]
Its working in 1.8, Thank you
