### ISSUE TITLE
Unable to use PAUSE in convo file. 

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-core#434]
**Describe the bug**
Unable to use PAUSE in convo file. 

- error.convo.txt
error check

#me
PAUSE 1000
hi

#bot
hi

Expected Result : 
Waiting 1sec before sending input to bot

Botium Bindings : 2.0.23

Error : 
Error: Failed to parse conversation. Invalid text: 'hi' in convo:
 PAUSE 1000
hi

    at lines.forEach.rawLine (/home/mtech/botium-test/node_modules/botium-core/src/scripting/helper.js:54:19)
    at Array.forEach (<anonymous>)
    at module.exports.linesToConvoStep (/home/mtech/botium-test/node_modules/botium-core/src/scripting/helper.js:28:9)
    at parseMsg (/home/mtech/botium-test/node_modules/botium-core/src/scripting/CompilerTxt.js:69:14)
    at pushPrev (/home/mtech/botium-test/node_modules/botium-core/src/scripting/CompilerTxt.js:79:34)
    at lines.forEach (/home/mtech/botium-test/node_modules/botium-core/src/scripting/CompilerTxt.js:93:9)
    at Array.forEach (<anonymous>)
    at CompilerTxt._compileConvo (/home/mtech/botium-test/node_modules/botium-core/src/scripting/CompilerTxt.js:89:11)
    at CompilerTxt.Compile (/home/mtech/botium-test/node_modules/botium-core/src/scripting/CompilerTxt.js:43:19)
    at ScriptingProvider.Compile (/home/mtech/botium-test/node_modules/botium-core/src/scripting/ScriptingProvider.js:361:21)
    at ScriptingProvider.ReadScript (/home/mtech/botium-test/node_modules/botium-core/src/scripting/ScriptingProvider.js:423:25)
    at ReadScriptsFromDirectory.filelist.forEach (/home/mtech/botium-test/node_modules/botium-core/src/scripting/ScriptingProvider.js:396:71)
    at Array.forEach (<anonymous>)
    at ScriptingProvider.ReadScriptsFromDirectory (/home/mtech/botium-test/node_modules/botium-core/src/scripting/ScriptingProvider.js:395:14)
    at convodirs.forEach (/home/mtech/botium-test/node_modules/botium-bindings/src/BotiumBindings.js:104:23)
    at Array.forEach (<anonymous>)
    at BotiumBindings.setupTestSuite (/home/mtech/botium-test/node_modules/botium-bindings/src/BotiumBindings.js:103:22)
    at setupMochaTestCases (/home/mtech/botium-test/node_modules/botium-bindings/src/helpers/mocha.js:10:6)
    at Suite.describe (/home/mtech/botium-test/node_modules/botium-bindings/src/helpers/mocha.js:42:5)
    at Object.create (/home/mtech/botium-test/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/home/mtech/botium-test/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.setupMochaTestSuite (/home/mtech/botium-test/node_modules/botium-bindings/src/helpers/mocha.js:24:3)
    at Object.<anonymous> (/home/mtech/botium-test/spec/email.spec.js:9:35)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/mtech/botium-test/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/mtech/botium-test/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/mtech/botium-test/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/home/mtech/botium-test/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/home/mtech/botium-test/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (/home/mtech/botium-test/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/home/mtech/botium-test/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/mtech/botium-test/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/home/mtech/botium-test/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/mtech/botium-test/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/home/mtech/botium-test/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by codeforequity-at** [comment]
Logic Hooks and User Input Methods always have to be placed below all text in the convo files, as they are always executed at the last possible point in the processing pipeline.

See https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491664/Botium+Scripting+-+BotiumScript


The error message could be more descriptive of course.

**Comment by radhabasida** [comment]
In the previous versions, it was working with above convo file.  After updating the botium-bindings to latest version, this issue is coming

**Comment by codeforequity-at** [comment]
We had to change this in order to allow more flexible customizations for asserters and logic hooks.
The text to assert is always the first section after the _#me_ tag, then the other asserters are expected.

For letting Botium wait before anything is sent, add the PAUSE to the previous _#bot_ section.

**Comment by radhabasida** [comment]
Thank you.. @codeforequity-at . I will check with above suggestion.
