### ISSUE TITLE
Exception when using botium-connector-watson-cli

### ISSUE THREAD

**Issue by maclean-stu** [codeforequity-at/botium-core#442]
It could be an installation issue, however I can connect to the emulator ok, but when I issue a watson import command I get the following error
botium-connector-watson-cli watsonimport watson-intents
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/botium-connector-watson/src/helpers.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by codeforequity-at** [comment]
thanks for the hint, there is a dependency missing. i will fix that. until then, either use botium-cli or run an additional "npm install -g mkdirp"

**Comment by maclean-stu** [comment]
Thanks., that resolved it.
