### ISSUE TITLE
Using special characters like & or / or ' in a user's message doesn't work

### ISSUE THREAD

**Issue by piotrjak** [codeforequity-at/botium-core#493]
**Describe the bug**
When I use special characters in a user's message then they are escaped.
If I try to escape them then I get an error.

**To Reproduce**
Steps to reproduce the behavior.

set a user's message that contains `&` or `/` or `'` character

#user 
Show me a market snapshot in David&Niagra

**Expected behavior**
I don't want it to be escaped if I use `\` character e.g. `\&`

**Screenshots and Log files**
When I don't use the \ character then I have to replace the characters myself in requestHook

![image](https://user-images.githubusercontent.com/45995385/76427083-2be25780-63ac-11ea-88e8-89c5342afeca.png)

If I use \ character then I get the error

#me
show me a market snapshot in David\&Niagra

```Multiple neighborhoods with varied utterances.Case1

    Multiple neighborhoods with varied utterances.Case1/Line 5: error sending to bot - composing body from SIMPLEREST_BODY_TEMPLATE failed (SyntaxError: Unexpected token & in JSON at position 112
        at JSON.parse (<anonymous>)

      at SimpleRestContainer._getMustachedVal (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:412:19)
      at SimpleRestContainer._getMustachedCap (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:407:17)
      at SimpleRestContainer._buildRequest (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:346:36)
      at SimpleRestContainer._doRequest (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:272:17)
      at SimpleRestContainer.UserSays (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:158:17)
      at node_modules/botium-core/src/containers/PluginConnectorContainer.js:169:37
      at node_modules/promise-retry/index.js:29:24
      at processTicksAndRejections (internal/process/task_queues.js:94:5))
      ########################################
      Multiple neighborhoods with varied utterances.Case1/Line 5: error sending to bot - composing body from SIMPLEREST_BODY_TEMPLATE failed (SyntaxError: Unexpected token & in JSON at position 112
          at JSON.parse (<anonymous>)
      at SimpleRestContainer._getMustachedVal (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:412:19)
      at SimpleRestContainer._getMustachedCap (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:407:17)
      at SimpleRestContainer._buildRequest (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:346:36)
      at SimpleRestContainer._doRequest (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:272:17)
      at SimpleRestContainer.UserSays (node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:158:17)
      at node_modules/botium-core/src/containers/PluginConnectorContainer.js:169:37
      at node_modules/promise-retry/index.js:29:24
      at processTicksAndRejections (internal/process/task_queues.js:94:5))
      ----------------------------------------
      {"err":{},"message":"Multiple neighborhoods with varied utterances.Case1/Line 5: error sending to bot - composing body from SIMPLEREST_BODY_TEMPLATE failed (SyntaxError: Unexpected token & in JSON at position 112\n    at JSON.parse (<anonymous>)\n    at SimpleRestContainer._getMustachedVal (/Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:412:19)\n    at SimpleRestContainer._getMustachedCap (/Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:407:17)\n    at SimpleRestContainer._buildRequest (/Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:346:36)\n    at SimpleRestContainer._doRequest (/Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:272:17)\n    at SimpleRestContainer.UserSays (/Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/plugins/SimpleRestContainer.js:158:17)\n    at /Users/x/Projects/chatbot-poc2/node_modules/botium-core/src/containers/PluginConnectorContainer.js:169:37\n    at /Users/x/Projects/chatbot-poc2/node_modules/promise-retry/index.js:29:24\n    at processTicksAndRejections (internal/process/task_queues.js:94:5))","input":{"sender":"me","channel":null,"messageText":"show me a market snapshot in David\\&Niagra","stepTag":"Line 5","not":false,"asserters":[],"logicHooks":[],"userInputs":[]}}
      at BotiumBindings.wrapBotiumError (node_modules/botium-bindings/src/BotiumBindings.js:98:12)
      at node_modules/botium-bindings/src/BotiumBindings.js:139:33
```

**Botium Flavour:**
Botium Bindings

**Botium Version**
Botium Bindings 2.0.29

**Additional context**

**Comment by codeforequity-at** [comment]
Can you please check your botium-core version - when looking at the line numbers, they seem outdated.

**Comment by codeforequity-at** [comment]
In my test with the latest botium-core version I only had troubles with the single quote character, the others worked. Although the JSON specification requires the single quote character to be escaped, the Javascript JSON parser fails on this. I checked in a workaround in the latest botium-core codebase.
