### ISSUE TITLE
botium-cli errors when other json files are in the same folder

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#541]
**Describe the bug**
I have upgraded botium-cli to 0.0.72 and when I run I get an error:

```
botium-cli run
/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

SyntaxError: Unexpected token } in JSON at position 361
    at JSON.parse (<anonymous>)
    at CompilerJson.Deserialize (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerJson.js:10:17)
    at CompilerJson.Compile (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerObjectBase.js:33:23)
    at ScriptingProvider.Compile (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:382:21)
    at ScriptingProvider.ReadScript (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:470:29)
    at /home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:417:71
    at Array.forEach (<anonymous>)
    at ScriptingProvider.ReadScriptsFromDirectory (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:416:14)
    at /home/static/.npm-global/lib/node_modules/botium-cli/src/run/index.js:109:14
    at Array.forEach (<anonymous>)
```

**To Reproduce**
Steps to reproduce the behavior.

1. Install version 0.0.72 `npm install -g botium-cli`
2. Have a service on port 5000 answering a JSON on /reply
3. Use this settings botium.json:

```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "bot-test",
      "CONTAINERMODE": "simplerest",
      "SCRIPTING_ENABLE_MEMORY": true,
      "SIMPLEREST_URL": "http://localhost:5000/reply",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_HEADERS_TEMPLATE": "{ \"content-type\": \"application/json; charset=utf-8\" }",
      "SIMPLEREST_BODY_TEMPLATE": "{ \"message\": \"{{msg.messageText}}\", \"user_id\": \"botium\" }",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.reply",
      "SIMPLEREST_INIT_TEXT": "reset_conversation"
    },
    "Sources": {},
    "Envs": {}
  }
}
```

**Expected behavior**
Test my bot =p

**Screenshots and Log files**
Stacktrace above, if you need more details I am happy to provide.

**Botium Flavour:**
 - Botium Box
 - Botium CLI - X
 - Botium Bindings ?

**Botium Version**
 - 0.0.72

**Additional context**
-

**Comment by codeforequity-at** [comment]
this happens when reading a json formatted botiumscript file, not when
using the http endpoint. whats in your convo directory ?

staticdev <notifications@github.com> schrieb am Fr., 24. Juli 2020, 22:22:

**Comment by staticdev** [comment]
I've made no changes to content in convos directory.. it is a list with many convo files:

```
ADEUSA_UTT.utterances.txt        idade.convo.txt
adeus.convo.txt                  IDADEQ_UTT.utterances.txt
adeus.utterances.txt             namoro.convo.txt
ANIVERSARIOA_UTT.utterances.txt  NAMOROQ_UTT.utterances.txt
aniversario.convo.txt            oscar.convo.txt
ANIVERSARIOQ_UTT.utterances.txt  OSCARQ_UTT.utterances.txt
DIAANIVA_UTT.utterances.txt      PARABENSA_UTT.utterances.txt
diaaniversario.convo.txt         parabens.convo.txt
DIAANIVQ_UTT.utterances.txt      premios.convo.txt
DIANASCA_UTT.utterances.txt      RECOMENDACAOA_UTT.utterances.txt
dianascimento.convo.txt          recomendacao.convo.txt
DIANASCQ_UTT.utterances.txt      RECOMENDACAOQ_UTT.utterances.txt
diretor.convo.txt                
IDADEA_UTT.utterances.txt
```

**Comment by codeforequity-at** [comment]
can younpls run it with the --verbose flag

staticdev <notifications@github.com> schrieb am Fr., 24. Juli 2020, 23:27:

**Comment by staticdev** [comment]
botium-cli run --verbose
  botium-cli Using Botium configuration file ./botium.json +0ms
  botium-cli-run command options: {
  botium-cli-run   _: [ 'run' ],
  botium-cli-run   verbose: true,
  botium-cli-run   v: true,
  botium-cli-run   convos: [ '.' ],
  botium-cli-run   C: [ '.' ],
  botium-cli-run   config: './botium.json',
  botium-cli-run   c: './botium.json',
  botium-cli-run   output: 'spec',
  botium-cli-run   testsuitename: 'Botium Test-Suite',
  botium-cli-run   n: 'Botium Test-Suite',
  botium-cli-run   expandutterances: false,
  botium-cli-run   expandscriptingmemory: false,
  botium-cli-run   timeout: 60,
  botium-cli-run   '$0': '/home/static/.npm-global/bin/botium-cli'
  botium-cli-run } +0ms
  botium-cli-run Mocha Reporter "spec", options: undefined +0ms
  botium-core-BotDriver Loaded Botium configuration file ./botium.json +0ms
  botium-core-BotDriver Loaded Botium configuration file ./botium.json +0ms
  botium-core-BotDriver Changed capability CONFIG to "./botium.json" using environment variables. +1ms
  botium-core-BotDriver BuildCompiler: Capabilites: {
  botium-core-BotDriver   PROJECTNAME: 'bot-test',
  botium-core-BotDriver   TESTSESSIONNAME: 'Botium Test Session',
  botium-core-BotDriver   TEMPDIR: 'botiumwork',
  botium-core-BotDriver   CLEANUPTEMPDIR: true,
  botium-core-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-core-BotDriver   SIMULATE_WRITING_SPEED: false,
  botium-core-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
  botium-core-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
  botium-core-BotDriver   DOCKERMACHINE: false,
  botium-core-BotDriver   DOCKERIMAGE: 'node:boron',
  botium-core-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
  botium-core-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
  botium-core-BotDriver   BOT_HEALTH_STATUS: 200,
  botium-core-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
  botium-core-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  botium-core-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  botium-core-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  botium-core-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  botium-core-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  botium-core-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  botium-core-BotDriver   SIMPLEREST_PING_RETRIES: 6,
  botium-core-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_PING_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_PING_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_STOP_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_STOP_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_POLL_VERB: 'GET',
  botium-core-BotDriver   SIMPLEREST_POLL_INTERVAL: 1000,
  botium-core-BotDriver   SIMPLEREST_POLL_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_METHOD: 'POST',
  botium-core-BotDriver   SIMPLEREST_TIMEOUT: 10000,
  botium-core-BotDriver   SIMPLEREST_EXTRA_OPTIONS: {},
  botium-core-BotDriver   SIMPLEREST_STRICT_SSL: true,
  botium-core-BotDriver   SIMPLEREST_INBOUND_UPDATE_CONTEXT: true,
  botium-core-BotDriver   SIMPLEREST_CONTEXT_MERGE_OR_REPLACE: 'MERGE',
  botium-core-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-core-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  botium-core-BotDriver   SCRIPTING_XLSX_HASHEADERS: true,
  botium-core-BotDriver   SCRIPTING_CSV_SKIP_HEADER: true,
  botium-core-BotDriver   SCRIPTING_CSV_QUOTE: '"',
  botium-core-BotDriver   SCRIPTING_CSV_ESCAPE: '"',
  botium-core-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-core-BotDriver   SCRIPTING_ENABLE_MEMORY: true,
  botium-core-BotDriver   SCRIPTING_ENABLE_MULTIPLE_ASSERT_ERRORS: false,
  botium-core-BotDriver   SCRIPTING_MATCHING_MODE: 'wildcardIgnoreCase',
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
  botium-core-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  botium-core-BotDriver   SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
  botium-core-BotDriver   ASSERTERS: [],
  botium-core-BotDriver   LOGIC_HOOKS: [],
  botium-core-BotDriver   USER_INPUTS: [],
  botium-core-BotDriver   CONTAINERMODE: 'simplerest',
  botium-core-BotDriver   SIMPLEREST_URL: 'http://minikube:30000/reply',
  botium-core-BotDriver   SIMPLEREST_HEADERS_TEMPLATE: { 'content-type': 'application/json; charset=utf-8' },
  botium-core-BotDriver   SIMPLEREST_BODY_TEMPLATE: { message: '{{msg.messageText}}', user_id: 'botium' },
  botium-core-BotDriver   SIMPLEREST_RESPONSE_JSONPATH: '$.reply',
  botium-core-BotDriver   SIMPLEREST_INIT_TEXT: 'resetvars205658',
  botium-core-BotDriver   CONFIG: './botium.json'
  botium-core-BotDriver } +0ms
  botium-core-ScriptingProvider Using matching mode: wildcardIgnoreCase +0ms
  botium-core-asserterUtils Loaded Default asserter - [
  botium-core-asserterUtils   'BUTTONS',              'MEDIA',
  botium-core-asserterUtils   'CARDS',                'PAUSE_ASSERTER',
  botium-core-asserterUtils   'JSON_PATH',            'RESPONSE_LENGTH',
  botium-core-asserterUtils   'FORMS',                'ENTITIES',
  botium-core-asserterUtils   'ENTITY_VALUES',        'ENTITY_CONTENT',
  botium-core-asserterUtils   'INTENT',               'INTENT_UNIQUE',
  botium-core-asserterUtils   'INTENT_CONFIDENCE',    'TEXT_CONTAINS_ANY',
  botium-core-asserterUtils   'TEXT_CONTAINS_ANY_IC', 'TEXT_CONTAINS_ALL',
  botium-core-asserterUtils   'TEXT_CONTAINS_ALL_IC', 'TEXT_WILDCARD_ANY',
  botium-core-asserterUtils   'TEXT_WILDCARD_ANY_IC', 'TEXT_WILDCARD_ALL',
  botium-core-asserterUtils   'TEXT_WILDCARD_ALL_IC', 'TEXT_REGEXP_ANY',
  botium-core-asserterUtils   'TEXT_REGEXP_ANY_IC',   'TEXT_REGEXP_ALL',
  botium-core-asserterUtils   'TEXT_REGEXP_ALL_IC',   'TEXT_EQUALS',
  botium-core-asserterUtils   'TEXT_EQUALS_IC',       'TEXT',
  botium-core-asserterUtils   'TEXT_IC'
  botium-core-asserterUtils ] +0ms
  botium-core-asserterUtils Loaded Default logic hook - [
  botium-core-asserterUtils   'PAUSE',
  botium-core-asserterUtils   'WAITFORBOT',
  botium-core-asserterUtils   'SET_SCRIPTING_MEMORY',
  botium-core-asserterUtils   'CLEAR_SCRIPTING_MEMORY',
  botium-core-asserterUtils   'ASSIGN_SCRIPTING_MEMORY',
  botium-core-asserterUtils   'UPDATE_CUSTOM',
  botium-core-asserterUtils   'INCLUDE'
  botium-core-asserterUtils ] +0ms
  botium-core-asserterUtils Loaded Default user input - [ 'BUTTON', 'MEDIA', 'FORM' ] +1ms
  botium-core-ScriptingProvider ReadConvosFromDirectory(.) found filenames: botium_grpc.json,botium.json,convos/adeus.convo.txt,convos/adeus.utterances.txt,convos/ADEUSA_UTT.utterances.txt,convos/aniversario.convo.txt,convos/ANIVERSARIOA_UTT.utterances.txt,convos/ANIVERSARIOQ_UTT.utterances.txt,convos/DIAANIVA_UTT.utterances.txt,convos/diaaniversario.convo.txt,convos/DIAANIVQ_UTT.utterances.txt,convos/DIANASCA_UTT.utterances.txt,convos/dianascimento.convo.txt,convos/DIANASCQ_UTT.utterances.txt,convos/diretor.convo.txt,convos/idade.convo.txt,convos/IDADEA_UTT.utterances.txt,convos/IDADEQ_UTT.utterances.txt,convos/namoro.convo.txt,convos/NAMOROQ_UTT.utterances.txt,convos/oscar.convo.txt,convos/OSCARQ_UTT.utterances.txt,convos/parabens.convo.txt,convos/PARABENSA_UTT.utterances.txt,convos/premios.convo.txt,convos/recomendacao.convo.txt,convos/RECOMENDACAOA_UTT.utterances.txt,convos/RECOMENDACAOQ_UTT.utterances.txt,README.md +9ms
/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

SyntaxError: Unexpected token } in JSON at position 361
    at JSON.parse (<anonymous>)
    at CompilerJson.Deserialize (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerJson.js:10:17)
    at CompilerJson.Compile (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/CompilerObjectBase.js:33:23)
    at ScriptingProvider.Compile (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:382:21)
    at ScriptingProvider.ReadScript (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:470:29)
    at /home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:417:71
    at Array.forEach (<anonymous>)
    at ScriptingProvider.ReadScriptsFromDirectory (/home/static/.npm-global/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:416:14)
    at /home/static/.npm-global/lib/node_modules/botium-cli/src/run/index.js:109:14
    at Array.forEach (<anonymous>)

**Comment by codeforequity-at** [comment]
botium reads all files from current directory. there are json files as
well, one of them is malformed. try to add the "--convos ./convos" option
to restrict botium to the convos directory

staticdev <notifications@github.com> schrieb am Sa., 25. Juli 2020, 20:02:

**Comment by staticdev** [comment]
@codeforequity-at ok, that trick worked but it is not very intuitive since the problem wasn't the convos folder but the other JSON on the folder called botium_grpc.json.

When I took this botium_grpc.json from the folder the error stopped and didn't need `--convos ./convos`. Since the default is `botium.json` this other json shouldn't be ignored?

**Comment by codeforequity-at** [comment]
No, Botium can read .json files, so it should not ignore those files. But it should definitely print what file caused the problem.

**Comment by codeforequity-at** [comment]
Fixed with latest release
