### ISSUE TITLE
Issue with dialogflow connector:  no such type: google.rpc.ErrorInfo

### ISSUE THREAD

**Issue by HalaKuwatly** [codeforequity-at/botium-core#602]
**Describe the bug**
I am trying to run nlpanalytics with dialogflow, but I am getting an error during validation:
`Starting training.
Validation training failed: no such type: google.rpc.ErrorInfo
`

**To Reproduce**
`botium-cli nlpanalytics validate --config ./config/dialogflow.botium.json --train ./convos/db-train --test ./convos/db-test --output ./results/validate-dialogflow.csv --outputPredictions ./results/validate-dialogflow-predictions.csv`

My config contains:
```{
    "botium": {
        "Capabilities": {
            "PROJECTNAME": "Botium NLPAnalytics Dialoflow",
            "CONTAINERMODE": "dialogflow",
            "RATELIMIT_USERSAYS_MINTIME": 1000,
            "RATELIMIT_USERSAYS_MAXCONCURRENT": 1,
            "DIALOGFLOW_NLP_PROJECT_ID": "****l",
            "DIALOGFLOW_NLP_CLIENT_EMAIL": "****",
            "DIALOGFLOW_NLP_PRIVATE_KEY": "****"
        }
    }
}
```
**Logs:**
I tried to print the stack trace if that helps:
```
Error: no such type: google.rpc.ErrorInfo
    at Root.lookupType (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/protobufjs/src/namespace.js:382:15)
    at FallbackErrorDecoder.decodeProtobufAny (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:35:32)
    at /home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:50:56
    at Array.map (<anonymous>)
    at FallbackErrorDecoder.decodeRpcStatus (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:50:37)
    at FallbackErrorDecoder.decodeErrorFromBuffer (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:63:46)
    at /home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallback.js:313:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  note: 'Exception occurred in retry method that was not classified as transient'
} Error: no such type: google.rpc.ErrorInfo
    at Root.lookupType (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/protobufjs/src/namespace.js:382:15)
    at FallbackErrorDecoder.decodeProtobufAny (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:35:32)
    at /home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:50:56
    at Array.map (<anonymous>)
    at FallbackErrorDecoder.decodeRpcStatus (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:50:37)
    at FallbackErrorDecoder.decodeErrorFromBuffer (/home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallbackError.js:63:46)
    at /home/hala/anaconda3/envs/py3/lib/node_modules/botium-connector-dialogflow/node_modules/google-gax/build/src/fallback.js:313:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
**Botium Flavour:**
 - Botium CLI

**Comment by codeforequity-at** [comment]
Will have to take a look. Will come back as soon as I have hints.

**Comment by codeforequity-at** [comment]
I think you are using this repository: https://github.com/codeforequity-at/botium-samples-nlpanalytics ?

I updated the NPM-dependencies there, and I suggest you try to either do a fresh clone, or you remove the _package-lock.json_ file and the _node_modules_ directory and do an _npm install_ again afterwards.

Please give me feedback if this helped.

**Comment by HalaKuwatly** [comment]
Thanks for your reply.
Yes I am using  https://github.com/codeforequity-at/botium-samples-nlpanalytics
I tried both removing `package-lock.json` file and the `node_modules` directory and recloning the repo. But I'm still getting the same error
```
Starting training.
Validation training failed: no such type: google.rpc.ErrorInfo
```

**Comment by codeforequity-at** [comment]
then maybe a matter of the Node.js version ? what version are you using ?

**Comment by HalaKuwatly** [comment]
`npm: '6.14.5'`

**Comment by HalaKuwatly** [comment]
I just upgraded node to `v15.6.0` and npm to `7.4.0`
still getting the same error :(

**Comment by codeforequity-at** [comment]
Honestly, no idea. Is there happening anything unusual when running _npm install_ ?

You can try to use the Botium CLI Docker image, everything is pre-installed in there.

**Comment by HalaKuwatly** [comment]
The issue turned out to be that API calls are not enabled for my dialogflow project.
