### ISSUE TITLE
Directline v3 - getting back undefined all the time

### ISSUE THREAD

**Issue by sebastianstephan** [codeforequity-at/botium-core#61]
Hi there, I am testing our deployed directline chatbot. I wanted to test the connection with a very simple test case. Here is my code.

```
const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source

function assert (expected, actual) {
    if (!actual || actual.indexOf(expected) < 0) {
      console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
    } else {
      console.log(`SUCCESS: Got Expected <${expected}>`)
    }
  }

const driver = new BotDriver()
  .setCapability(Capabilities.PROJECTNAME, 'My_AutomaticTesting')
  .setCapability(Capabilities.CONTAINERMODE, 'directline3')
  .setCapability(Capabilities.DIRECTLINE3_SECRET, 'XXXX')
  .setCapability(Capabilities.DIRECTLINE3_WEBSOCKET, true)
  .setCapability(Capabilities.DIRECTLINE3_POLLINGINTERVAL, 100)
  .setEnv('DEBUG', '*')

  driver.BuildFluent()
  .Start()
  .UserSaysText('Hallo')
  .WaitBotSaysText(console.log)
  .WaitBotSaysText(console.log)
  //.WaitBotSaysText((text) => assert('Hallo', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
```

And I am also using the botium.json with the kind of same configuration.

I am now getting this as console output:

```
> node botiumTests.js 
undefined
undefined
READY
```

I dont know what's the issue. How can I get deeper into debugging the Chatbot - is there a debug mode and if so, how do I enable it?

**Comment by codeforequity-at** [comment]
Yes, debug mode is available:
https://github.com/codeforequity-at/botium-core/wiki/Troubleshooting

Pls attach resulting output here fir assistance

Am 20.05.2018 12:03 schrieb "sebastianstephan" <notifications@github.com>:

Hi there, I am testing our deployed directline chatbot. I wanted to test
the connection with a very simple test case. Here is my code.

const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source

function assert (expected, actual) {
    if (!actual || actual.indexOf(expected) < 0) {
      console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
    } else {
      console.log(`SUCCESS: Got Expected <${expected}>`)
    }
  }

const driver = new BotDriver()
  .setCapability(Capabilities.PROJECTNAME, 'My_AutomaticTesting')
  .setCapability(Capabilities.CONTAINERMODE, 'directline3')
  .setCapability(Capabilities.DIRECTLINE3_SECRET, 'XXXX')
  .setCapability(Capabilities.DIRECTLINE3_WEBSOCKET, true)
  .setCapability(Capabilities.DIRECTLINE3_POLLINGINTERVAL, 100)
  .setEnv('DEBUG', '*')

  driver.BuildFluent()
  .Start()
  .UserSaysText('Hallo')
  .WaitBotSaysText(console.log)
  .WaitBotSaysText(console.log)
  //.WaitBotSaysText((text) => assert('Hallo', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })

And I am also using the botium.json with the kind of same configuration.

I am now getting this as console output:

> node botiumTests.js
undefined
undefined
READY

I dont know what's the issue. How can I get deeper into debugging the
Chatbot - is there a debug mode and if so, how do I enable it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeforequity-at/botium-core/issues/61>, or mute the
thread

**Comment by sebastianstephan** [comment]
Thanks, got debug output working.

this ist the output. I am trying to connect directly to the directline - the connection is working with our webchat with the directline key. I am not using docker mode (containermode: directline3).

```
Sebastian-MacBook-Pro:botium sebastianstephan$ node botiumTests.js 
  botium-BotDriver Loaded Botium configuration file ./botium.json +0ms
  botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Mia_AutomaticTesting',
  botium-BotDriver   TEMPDIR: 'botiumwork',
  botium-BotDriver   CLEANUPTEMPDIR: true,
  botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-BotDriver   CONTAINERMODE: 'directline3',
  botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
  botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
  botium-BotDriver   DOCKERMACHINE: false,
  botium-BotDriver   DOCKERIMAGE: 'node:boron',
  botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
  botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
  botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
  botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  botium-BotDriver   WATSONCONVERSATION_URL: 'https://gateway.watsonplatform.net/conversation/api',
  botium-BotDriver   WATSONCONVERSATION_VERSION_DATE: '2017-05-26',
  botium-BotDriver   WATSONCONVERSATION_COPY_WORKSPACE: false,
  botium-BotDriver   WATSONCONVERSATION_USE_INTENT: false,
  botium-BotDriver   SIMPLEREST_METHOD: 'GET',
  botium-BotDriver   DIALOGFLOW_LANGUAGE_CODE: 'en-US',
  botium-BotDriver   DIALOGFLOW_USE_INTENT: false,
  botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
  botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
  botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
  botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
  botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
  botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  botium-BotDriver   DIRECTLINE3_SECRET: 'MlyTqd94Uao.XXX.YYY.XXXXXXXXX1qqW9WL5OwQ4TpE2ycMN7ji-XXXXXXXXXX',
  botium-BotDriver   DIRECTLINE3_WEBSOCKET: false,
  botium-BotDriver   DIRECTLINE3_POLLINGINTERVAL: 1000,
  botium-BotDriver   undefined: 1000 } +5ms
  botium-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-BotDriver   GITPATH: 'git',
  botium-BotDriver   GITBRANCH: 'master',
  botium-BotDriver   GITDIR: '.' } +0ms
  botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
  botium-PluginConnectorContainer Botium plugin botium-connector-directline3 loaded +0ms
  botium-connector-directline3 Validate called +0ms
  botium-connector-directline3 Build called +1ms
  botium-connector-directline3 Start called +2ms
  botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at timeoutRequest (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/src/helpers/Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/node_modules/async/dist/async.js:4922:13)
  botium-BaseContainer     at ontimeout (timers.js:498:11)
  botium-BaseContainer     at tryOnTimeout (timers.js:323:5)
  botium-BaseContainer     at Timer.listOnTimeout (timers.js:290:5) +0ms
undefined
  botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at timeoutRequest (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/src/helpers/Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/node_modules/async/dist/async.js:4922:13)
  botium-BaseContainer     at ontimeout (timers.js:498:11)
  botium-BaseContainer     at tryOnTimeout (timers.js:323:5)
  botium-BaseContainer     at Timer.listOnTimeout (timers.js:290:5) +10s
undefined
  botium-connector-directline3 UserSays called +20s
  botium-connector-directline3 Posted activity, assigned ID  retry +2s
  botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at timeoutRequest (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/src/helpers/Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/node_modules/async/dist/async.js:4922:13)
  botium-BaseContainer     at ontimeout (timers.js:498:11)
  botium-BaseContainer     at tryOnTimeout (timers.js:323:5)
  botium-BaseContainer     at Timer.listOnTimeout (timers.js:290:5) +12s
undefined
  botium-connector-directline3 Stop called +10s
  botium-connector-directline3 Clean called +1ms
READY
Sebastian-MacBook-Pro:botium sebastianstephan$ 
```

**Comment by sebastianstephan** [comment]
Okay, I was trying around a little bit more and I got some weird behaviour. I am getting a connection to the bot - but ONLY if I send two messages to the bot. Otherwise I am getting a timeout.

This code results in a timeout:
```
  driver.BuildFluent()
  .Start()
  .UserSaysText('Hallo')
  .WaitBotSaysText(console.log)
  //.WaitBotSaysText((text) => assert('Hallo', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
```

OUTPUT:
```
 botium-BotDriver   DIRECTLINE3_WEBSOCKET: false,
  botium-BotDriver   DIRECTLINE3_POLLINGINTERVAL: 100,
  botium-BotDriver   undefined: 1000 } +4ms
  botium-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-BotDriver   GITPATH: 'git',
  botium-BotDriver   GITBRANCH: 'master',
  botium-BotDriver   GITDIR: '.' } +0ms
  botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +1ms
  botium-PluginConnectorContainer Botium plugin botium-connector-directline3 loaded +0ms
  botium-connector-directline3 Validate called +0ms
  botium-connector-directline3 Build called +0ms
  botium-connector-directline3 Start called +2ms
  botium-connector-directline3 UserSays called +21ms
  botium-connector-directline3 Posted activity, assigned ID  retry +2s
  botium-BaseContainer WaitBotSays error Error: Queue.pop timeout after 10000
  botium-BaseContainer     at timeoutRequest (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/src/helpers/Queue.js:46:18)
  botium-BaseContainer     at Timeout.timeoutCallback [as _onTimeout] (/Users/sebastianstephan/workspace/botium/node_modules/botium-core/node_modules/async/dist/async.js:4922:13)
  botium-BaseContainer     at ontimeout (timers.js:498:11)
  botium-BaseContainer     at tryOnTimeout (timers.js:323:5)
  botium-BaseContainer     at Timer.listOnTimeout (timers.js:290:5) +0ms
undefined
  botium-connector-directline3 Stop called +10s
  botium-connector-directline3 Clean called +1ms
READY
```

And this code:
```
  driver.BuildFluent()
  .Start()
  .UserSaysText('Hallo')
  .UserSaysText('Hallo')
  .WaitBotSaysText(console.log)
  //.WaitBotSaysText((text) => assert('Hallo', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
```

is bringing this output:
 ```
...botium-BotDriver   DIRECTLINE3_WEBSOCKET: false,
  botium-BotDriver   DIRECTLINE3_POLLINGINTERVAL: 100,
  botium-BotDriver   undefined: 1000 } +5ms
  botium-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-BotDriver   GITPATH: 'git',
  botium-BotDriver   GITBRANCH: 'master',
  botium-BotDriver   GITDIR: '.' } +0ms
  botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
  botium-PluginConnectorContainer Botium plugin botium-connector-directline3 loaded +0ms
  botium-connector-directline3 Validate called +0ms
  botium-connector-directline3 Build called +0ms
  botium-connector-directline3 Start called +2ms
  botium-connector-directline3 UserSays called +22ms
  botium-connector-directline3 Posted activity, assigned ID  retry +2s
  botium-connector-directline3 UserSays called +1ms
  botium-connector-directline3 received message  { type: 'message',
  id: '7ZAEXcUr13NJ91gkCtDZ93|0000001',
  timestamp: '2018-05-22T11:36:10.7315587Z',
  localTimestamp: '2018-05-22T11:36:10.6413411+00:00',
  channelId: 'directline',
  from: { id: 'dev-ana', name: 'dev-ana' },
  conversation: { id: '7ZAEXcUr13NJ91gkCtDZ93' },
  attachmentLayout: 'carousel',
  text: 'A warm welcome',
  attachments: [],
  entities: [],
  channelData: { clientActivityId: '8457a88a-5908-4268-b495-1d8b4f8730c0' },
  replyToId: '7ZAEXcUr13NJ91gkCtDZ93|0000000' } +5s
  botium-connector-directline3 received message  { type: 'message',
  id: '7ZAEXcUr13NJ91gkCtDZ93|0000001',
  timestamp: '2018-05-22T11:36:10.7315587Z',
  localTimestamp: '2018-05-22T11:36:10.6413411+00:00',
  channelId: 'directline',
  from: { id: 'dev-ana', name: 'dev-ana' },
  conversation: { id: '7ZAEXcUr13NJ91gkCtDZ93' },
  attachmentLayout: 'carousel',
  text: 'A warm welcome',
  attachments: [],
  entities: [],
  channelData: { clientActivityId: '8457a88a-5908-4268-b495-1d8b4f8730c0' },
  replyToId: '7ZAEXcUr13NJ91gkCtDZ93|0000000' } +126ms
  botium-connector-directline3 received message  { type: 'message',
  id: '7ZAEXcUr13NJ91gkCtDZ93|0000002',
  timestamp: '2018-05-22T11:36:13.4651026Z',
  localTimestamp: '2018-05-22T11:36:13.3369583+00:00',
  channelId: 'directline',
  from: { id: 'dev-ana', name: 'dev-ana' },
  conversation: { id: '7ZAEXcUr13NJ91gkCtDZ93' },
  attachmentLayout: 'carousel',
  text: 'What can I do for you?',
  attachments: [],
  entities: [],
  channelData: { clientActivityId: 'b7516950-1244-456a-8408-acb60a35f342' },
  replyToId: '7ZAEXcUr13NJ91gkCtDZ93|0000000' } +3s
  botium-connector-directline3 received message  { type: 'message',
  id: '7ZAEXcUr13NJ91gkCtDZ93|0000002',
  timestamp: '2018-05-22T11:36:13.4651026Z',
  localTimestamp: '2018-05-22T11:36:13.3369583+00:00',
  channelId: 'directline',
  from: { id: 'dev-ana', name: 'dev-ana' },
  conversation: { id: '7ZAEXcUr13NJ91gkCtDZ93' },
  attachmentLayout: 'carousel',
  text: 'What can I do for you?',
  attachments: [],
  entities: [],
  channelData: { clientActivityId: 'b7516950-1244-456a-8408-acb60a35f342' },
  replyToId: '7ZAEXcUr13NJ91gkCtDZ93|0000000' } +80ms
  botium-connector-directline3 Posted activity, assigned ID  7ZAEXcUr13NJ91gkCtDZ93|0000000 +481ms
A warm welcome
  botium-connector-directline3 Stop called +2ms
  botium-connector-directline3 Clean called +1ms
READY

```

**Comment by codeforequity-at** [comment]
There seems to be some failure in this botium connector - obviously it
receives what's replied from the bot, as seen in the debug output, but it
fails to forward it to the client code.
Easiest way to help would be if you provided you test project to me
(including google secret), but not here in public but by email (
florian.treml@botium.at). I can do some debugging then.

2018-05-22 13:38 GMT+02:00 sebastianstephan <notifications@github.com>:

**Comment by codeforequity-at** [comment]
email not received - pls place package on some file shareing service and send me the link

**Comment by codeforequity-at** [comment]
Closed for long inactivity.
