### ISSUE TITLE
Conversation parsing fails if a message starts with a # sign

### ISSUE THREAD

**Issue by andrewrfreed** [codeforequity-at/botium-core#621]
**Describe the bug**
Botium fails to parse conversation if the bot's message or user's message starts with `#`.

**To Reproduce**
Test case:

```
API call test - In my system, API responses always start with pound signs
  
#bot
How can I help you

#me
make an API call

#bot
##API_SUCCESS##
```

**Expected behavior**

**Screenshots and Log files**
```
/Users/afreed/Code/personal-botium-tester/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

BotiumError: ReadScript - an error occurred at 'happy-path-9-digit-payment-status.convo.txt' file: Failed to parse conversation. Section "#API_SUCCESS##" unknown.
    at botiumErrorFromErr (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/BotiumError.js:85:12)
    at ScriptingProvider.ReadScript (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:530:13)
    at /Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:459:71
    at Array.forEach (<anonymous>)
    at ScriptingProvider.ReadScriptsFromDirectory (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:458:14)
    at /Users/afreed/Code/personal-botium-tester/node_modules/botium-cli/src/run/index.js:109:14
    at Array.forEach (<anonymous>)
    at handler (/Users/afreed/Code/personal-botium-tester/node_modules/botium-cli/src/run/index.js:108:15)
    at Object.builder.handler (/Users/afreed/Code/personal-botium-tester/node_modules/botium-cli/bin/botium-cli.js:34:7)
    at Object.runCommand (/Users/afreed/Code/personal-botium-tester/node_modules/yargs/build/index.cjs:446:48) {
  context: {
    err: Error: Failed to parse conversation. Section "#API_SUCCESS##" unknown.
        at linesToConvoStep (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/helper.js:78:38)
        at parseMsg (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/CompilerTxt.js:69:14)
        at pushPrev (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/CompilerTxt.js:79:34)
        at /Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/CompilerTxt.js:93:9
        at Array.forEach (<anonymous>)
        at CompilerTxt._compileConvo (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/CompilerTxt.js:89:11)
        at CompilerTxt.Compile (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/CompilerTxt.js:43:19)
        at ScriptingProvider.Compile (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:414:21)
        at ScriptingProvider.ReadScript (/Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:500:27)
        at /Users/afreed/Code/personal-botium-tester/node_modules/botium-core/src/scripting/ScriptingProvider.js:459:71,
    message: `ReadScript - an error occurred at 'happy-path-9-digit-payment-status.convo.txt' file: Failed to parse conversation. Section "#API_SUCCESS##" unknown.`
  }
}
```

**Botium Flavour:**
Botium Core with Watson bindings

**Botium Version**
Botium Core 1.12.1

**Additional context**
Solvable by updating `scripting/CompilerTxt.js`

I have locally tried two different updates for the line 92 `if (line && line.startsWith('#')) {` . 

First: `if (line && line.startsWith('#') && !line.startsWith('##')) {`

Second:  `if (line && (line.startsWith('#begin') || line.startsWith('#end') || line.startsWith('#me') || line.startsWith('#bot') || line.startsWith('#include'))) {`

Either solution is enough to fix my personal test. Neither solution is completely satisfactory - I suspect botium may add further `#` directives in the future.

**Comment by andrewrfreed** [comment]
Please feel free to use or reject:
https://github.com/codeforequity-at/botium-core/pull/622

I am not familiar with building Node.js applications

**Comment by codeforequity-at** [comment]
Added it to the _develop_ branch (see #621). Will be part of the next release.
