### ISSUE TITLE
Getting error consistently when 1 or 2 utterances from botium-bindings

### ISSUE THREAD

**Issue by ram-d** [codeforequity-at/botium-core#709]
**Describe the bug**
Hi, 
I am getting the following error for some utterances when I run the tests. The same utterance works fine the next time but the other utterance fails with the same error. It happens very frequently. Out of 400 tests, 4 to 5 are failing with this error.  Is this a timeout issue?

Error: Convos_fit-A005/UTT-L01/Cell A5: error sending to bot - Cannot read properties of undefined (reading 'error')
########################################
Convos_fit-A005/UTT-L01/Cell A5: error sending to bot - Cannot read properties of undefined (reading 'error')
------------ TRANSCRIPT ----------------------------
#me: what day is today
    at BotiumBindings.wrapBotiumError (/Users/testuser/specs/node_modules/botium-bindings/src/BotiumBindings.js:77:14)
    at /Users/testuser/specs/node_modules/botium-bindings/src/BotiumBindings.js:134:33
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To Reproduce**

**Expected behavior**
All tests need to run successfully. It only fails when the test is run automatically but succeeds when we run it using botium-cli emulator.

**Screenshots and Log files**
If applicable, add screenshots and/or logfiles to help explain your problem.
 - [How to get logs from Botium Box](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/29360129/Enable+Diagnostics+and+Inspect+Logs)
 - [How to get logs from Botium Bindings](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/426128/Troubleshooting)
 - For Botium CLI, add the *--verbose* command line switch

**Botium Flavour:**
 - Botium Box ?
 - Botium CLI ?
 - Botium Bindings ?

**Botium Version**
 - "botium-cli": "^1.1.0",
 - "botium-bindings": "^2.1.13",

**Additional context**

**Comment by ujja** [comment]
It looks Botium throws exception while it handles an exception. Could you attach logs please?

**Comment by ram-d** [comment]
@ujja , it's hard to capture the logs because it fails only when I run 150+ tests and it consistently fails with some utterances that worked fine in the previous test run.

**Comment by ujja** [comment]
Well, without logs we cant say anything.

What you mean with "test is run automatically"?
