### ISSUE TITLE
npm install fails on grpc@1.7.3 (403)

### ISSUE THREAD

**Issue by anneq** [codeforequity-at/botium-core#81]
When I follow the guide to install botium-core, the following command fails on installing grpc 1.7.3:
`npm install --save botium-core`

The main error is:
`node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz`

After that it tries to compile from source, which of course fails:

`In file included from ../deps/grpc/src/core/lib/channel/channel_stack.c:19:
../deps/grpc/src/core/lib/channel/channel_stack.h:38:10: fatal error: grpc/grpc.h: No such file or directory
 #include <grpc/grpc.h>
          ^~~~~~~~~~~~~
compilation terminated.`

If I manually follow the link to the binary, I indeed get a 403. I'm completely baffled here. How can the install depend on a private component from Google. This can never work, or the installation guide is missing a critical piece of information.

_________________________________________________________________

This is the complete error:
`npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.

> grpc@1.7.3 install /home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/build'
make: Entering directory '/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
make: *** [grpc.target.mk:399: Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
make: Leaving directory '/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.16.11-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.16.11-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v10.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.onstall script
In file included from ../deps/grpc/src/core/lib/channel/channel_stack.c:19:
../deps/grpc/src/core/lib/channel/channel_stack.h:38:10: fatal error: grpc/grpc.h: No such file or directory
 #include <grpc/grpc.h>
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [grpc.target.mk:399: Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o] Error 1
make: Leaving directory '/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.16.11-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/anne-ah/workspace/botium/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN botium@1.0.0 No description
npm WARN botium@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by codeforequity-at** [comment]
There are some troubles with this package, right. With one of the next Botium builds, the Dialogflow connector will be moved into a separate plugin, so that those problems will only affect users who want to use Dialogflow, not all Botium users.

A quick workaround would be, to run this command just before the Botium installation:

`npm install dialogflow --ignore-scripts`

It will get the dialogflow module then, but won't do all the other stuff causing the problems.

**Comment by anneq** [comment]
Limiting the problem to non-DialogFlow users will not help me, since that's exactly what I want to do: test it with DialogFlow. So I'm still hoping for a solution that works for everyone.

And I tried the command, but the error stays the same:
~/workspace/botium $ npm install dialogflow --ignore-scripts
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN botium@1.0.0 No repository field.

+ dialogflow@0.5.0
added 358 packages from 357 contributors and audited 1363 packages in 5.739s
found 0 vulnerabilities

~/workspace/botium $ npm install --save botium-core
npm WARN deprecated nomnom@1.5.2: Package no longer supported. Contact support@npmjs.com for more info.

> grpc@1.7.3 install /home/anne-ah/workspace/botium/node_modules/botium-core/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
  :
  :
  :

**Comment by codeforequity-at** [comment]
I moved the Dialogflow connector to a separate Botium plugin.
Please install now with:
```
> npm install botium-core
> npm install botium-connector-dialogflow
```

Botium now uses the latest Dialogflow library, so I think your problem should be fixed now (the precompiled libraries are available at the google servers).

**Comment by anneq** [comment]
That worked. Thanks for the quick response!
