### ISSUE TITLE
 Error: Unexpected error while acquiring application default credentials

### ISSUE THREAD

**Issue by mahmeds7777** [codeforequity-at/botium-core#94]
Hi.

We developed a Dialogflow agent, enabled the Google assistant integration, marked some of the intents to be only available after authentication, and setup account linking with our own Oauth server. In our dialogflow agent, we configured a fulfillment endpoint, which requires the accessToken to grant access to some resources. 

How do I go about testing the intents / fulfillment using Botium? Currently, I run into the following error when running:

`botium-cli import dialogflow-conversations`

`(node:35816) Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (C:\Users\mahmeds\AppData\Roaming\npm\node_modules\botium-cli\node_modules\google-auth-library\build\src\auth\googleauth.js:248:31)
    at step (C:\Users\mahmeds\AppData\Roaming\npm\node_modules\botium-cli\node_modules\google-auth-library\build\src\auth\googleauth.js:47:23)
    at Object.next (C:\Users\mahmeds\AppData\Roaming\npm\node_modules\botium-cli\node_modules\google-auth-library\build\src\auth\googleauth.js:28:53)
    at fulfilled (C:\Users\mahmeds\AppData\Roaming\npm\node_modules\botium-cli\node_modules\google-auth-library\build\src\auth\googleauth.js:19:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

New to this, so detailed instructions appreciated.

**Comment by mahmeds7777** [comment]
Yes, I have followed all the steps [here](https://chatbotsmagazine.com/3-steps-setup-automated-testing-for-google-assistant-and-dialogflow-de42937e57c6) up to the 

`botium-cli import dialogflow-conversations'    step where I encounter the error mentioned above.

I can interact with the intents when setting '"DIALOGFLOW_USE_INTENT": false' and using 'botium-cli emulator' but cannot import

**Comment by codeforequity-at** [comment]
I provided a fix in the latest botium-cli build!
